HEIGHT = 15
WIDTH = 15

CAPTION = "Helicopter battle"
SIZE = (WIDTH, HEIGHT)
FPS = 10

PROBABILITY_OF_STARTING_FIRE = 0.05 / FPS
PROBABILITY_OF_CLOUD = 0.05 / FPS
PROBABILITY_OF_LIGHTING = PROBABILITY_OF_CLOUD / 10

MAX_DURATION_OF_FIRE = 5 * 1000

MIN_DURATION_OF_CLOUDS = 1 * 1000
MAX_DURATION_OF_CLOUDS = 5 * 1000

UPGRADE_TANK_COST = 500
POINTS_FOR_EXTINGUISHING_FIRE = 100

START_LIVES = 20
LIVES_DECREMENT_ON_LIGHTING = 1
ADD_LIVES_COST = 1000
COUNT_ADDED_LIVES = 10

file_tileset = "images/tilemap_packed_32.png"
TILE_SIZE = 32

water_index_file = open("water_index.txt", "r")
water_index = list(map(int, water_index_file.readline().split()))
